services:
  postgres:
    container_name: fresco-dev-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", '-U', 'postgres']
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  postgres:
    name: fresco-dev-db-volume